steps:
  - name: "node:22"
    dir: "frontend/web-admin"
    entrypoint: "bash"
    args: ["-c", "npm install && npm run build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "frontend/web-admin"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy app.yaml --quiet"]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY